version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest
    container_name: backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest
    container_name: frontend
    env_file: .env
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest
    container_name: gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
